{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "policyreporter.fullname" . }}
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "policyreporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: "ServiceAccount"
  name: {{ include "policyreporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
