{{- if or .Values.emailReports.summary.enabled .Values.emailReports.violations.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "policyreporter.fullname" . }}-config-email-reports
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ tpl (.Files.Get "config-email-reports.yaml") . | b64enc }}
{{- end }}  