{{- if not .Values.existingTargetConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "policyreporter.fullname" . }}-config
  namespace: {{ include "policyreporter.namespace" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl (.Files.Get "config.yaml") . }}
{{- end }}
