{{- if not .Values.existingTargetConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "policyreporter.fullname" . }}-config
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ tpl (.Files.Get "config.yaml") . | b64enc }}
{{- end }}  