{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels: {{ include "policyreporter.labels" . | nindent 4 }}
  name: {{ include "policyreporter.fullname" . }}
spec:
  podSelector:
    matchLabels: {{- include "policyreporter.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: {{ .Values.global.port }}
  - from:
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress:
  - to:
    - podSelector:
        matchLabels: {{- include "ui.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.ui.service.port }}
  - to:
    ports:
    - protocol: TCP
      port: 6443
  {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
