{{- if .Values.ui.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels: {{ include "policyreporter.labels" . | nindent 4 }}
  name: {{ include "policyreporter.fullname" . }}
spec:
  podSelector:
    matchLabels: {{- include "policyreporter.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: {{ .Values.global.port }} 
  egress:
  - to:
    ports:
    - protocol: TCP
      port: {{ .Values.ui.service.port }} 
{{- end }}
