apiVersion: v1
kind: Secret
metadata:
  name: {{ include "policyreporter.fullname" . }}-targets
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ tpl (.Files.Get "config.yaml") . | b64enc }}