version: 2

builds:
  - id: policy-reporter
    mod_timestamp: "{{ .CommitTimestamp }}"
    binary: policy-reporter
    flags:
      - -trimpath
      - -tags="sqlite_unlock_notify"
    ldflags:
      - -s -w -linkmode external -extldflags "-static"
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=zig cc -target x86_64-linux-gnu{{- end }}
          {{- if eq .Arch "arm64" }}CC=zig cc -target aarch64-linux-gnu{{- end }}
        {{- else }}
          CC=clang
        {{- end }}

kos:
  - id: policy-reporter
    repositories:
      - ghcr.io/kyverno/policy-reporter
    tags:
      - '{{.Tag}}'
      - '{{ if not .Prerelease }}latest{{ end }}' 
    base_import_paths: true
    base_image: gcr.io/distroless/base-debian12
    platforms:
      - linux/amd64
      - linux/arm64
    bare: true
    sbom: spdx
    flags:
      - -trimpath
    ldflags:
      - -s -w

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --bundle=${signature}
      - ${artifact}
      - --yes
    artifacts: all
    output: true

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - sign
      - ${artifact}
      - --yes

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

snapshot:
  version_template: '{{ incpatch .Version }}-next'

release:
  prerelease: auto
