version: 2

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

dockers_v2:
  - id: policy-reporter
    images:
      - ghcr.io/kyverno/policy-reporter
    tags:
      - '{{.Tag}}'
      - "{{.Version}}"
      - '{{ if not .Prerelease }}latest{{ end }}'
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/s390x
    sbom: true
    build_args:
      LD_FLAGS: '-s -w -linkmode external -extldflags "-static"'
      X: main.Version={{ .Tag }}
    extra_files:
      - cmd
      - pkg
      - templates
      - go.mod
      - go.sum
      - main.go
      - LICENSE.md

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --bundle=${signature}
      - ${artifact}
      - --yes
    artifacts: all
    output: true

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - sign
      - ${artifact}
      - --yes

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: checksums.txt

docker_digests:
  name_template: "digests.txt"

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

snapshot:
  version_template: '{{ incpatch .Version }}-next'

release:
  prerelease: auto
