/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kyverno/policy-reporter/pkg/crd/api/targetconfig/v1alpha1"
)

// FakeTargetConfigs implements TargetConfigInterface
type FakeTargetConfigs struct {
	Fake *FakePolicyreporterV1alpha1
	ns   string
}

var targetconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("targetconfigs")

var targetconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("TargetConfig")

// Get takes name of the targetConfig, and returns the corresponding targetConfig object, and an error if there is any.
func (c *FakeTargetConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TargetConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(targetconfigsResource, c.ns, name), &v1alpha1.TargetConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TargetConfig), err
}

// List takes label and field selectors, and returns the list of TargetConfigs that match those selectors.
func (c *FakeTargetConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TargetConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(targetconfigsResource, targetconfigsKind, c.ns, opts), &v1alpha1.TargetConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TargetConfigList{ListMeta: obj.(*v1alpha1.TargetConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.TargetConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested targetConfigs.
func (c *FakeTargetConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(targetconfigsResource, c.ns, opts))

}

// Create takes the representation of a targetConfig and creates it.  Returns the server's representation of the targetConfig, and an error, if there is any.
func (c *FakeTargetConfigs) Create(ctx context.Context, targetConfig *v1alpha1.TargetConfig, opts v1.CreateOptions) (result *v1alpha1.TargetConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(targetconfigsResource, c.ns, targetConfig), &v1alpha1.TargetConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TargetConfig), err
}

// Update takes the representation of a targetConfig and updates it. Returns the server's representation of the targetConfig, and an error, if there is any.
func (c *FakeTargetConfigs) Update(ctx context.Context, targetConfig *v1alpha1.TargetConfig, opts v1.UpdateOptions) (result *v1alpha1.TargetConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(targetconfigsResource, c.ns, targetConfig), &v1alpha1.TargetConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TargetConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTargetConfigs) UpdateStatus(ctx context.Context, targetConfig *v1alpha1.TargetConfig, opts v1.UpdateOptions) (*v1alpha1.TargetConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(targetconfigsResource, "status", c.ns, targetConfig), &v1alpha1.TargetConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TargetConfig), err
}

// Delete takes name of the targetConfig and deletes it. Returns an error if one occurs.
func (c *FakeTargetConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(targetconfigsResource, c.ns, name, opts), &v1alpha1.TargetConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTargetConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(targetconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TargetConfigList{})
	return err
}

// Patch applies the patch and returns the patched targetConfig.
func (c *FakeTargetConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TargetConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(targetconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TargetConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TargetConfig), err
}
