blockReports:
  {{- toYaml .Values.blockReports | nindent 2 }}

leaderElection:
  enabled: {{ include "policyreporter.leaderElection" . }}
  releaseOnCancel: {{ .Values.leaderElection.releaseOnCancel }}
  leaseDuration: {{ .Values.leaderElection.leaseDuration }}
  renewDeadline: {{ .Values.leaderElection.renewDeadline }}
  retryPeriod: {{ .Values.leaderElection.retryPeriod }}
