blockReports:
  {{- toYaml .Values.blockReports | nindent 2 }}

leaderElection:
  enabled: {{ or .Values.leaderElection.enabled (gt (int .Values.replicaCount) 1) }}
  releaseOnCancel: {{ .Values.leaderElection.releaseOnCancel }}
  leaseDuration: {{ .Values.leaderElection.leaseDuration }}
  renewDeadline: {{ .Values.leaderElection.renewDeadline }}
  retryPeriod: {{ .Values.leaderElection.retryPeriod }}

logging:
  encoding: {{ .Values.logging.encoding }}
  logLevel: {{ include "kyvernoplugin.logLevel" . }}
  development: {{ .Values.logging.development }}

api:
  logging: {{ .Values.api.logging }}
  basicAuth:
    username: {{ .Values.global.basicAuth.username }}
    password: {{ .Values.global.basicAuth.password }}
    secretRef: {{ .Values.global.basicAuth.secretRef }}
