blockReports:
  {{- toYaml .Values.blockReports | nindent 2 }}

leaderElection:
  enabled: {{ or .Values.leaderElection.enabled (gt (int .Values.replicaCount) 1) }}
  releaseOnCancel: {{ .Values.leaderElection.releaseOnCancel }}
  leaseDuration: {{ .Values.leaderElection.leaseDuration }}
  renewDeadline: {{ .Values.leaderElection.renewDeadline }}
  retryPeriod: {{ .Values.leaderElection.retryPeriod }}
