//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfig) DeepCopyInto(out *AWSConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfig.
func (in *AWSConfig) DeepCopy() *AWSConfig {
	if in == nil {
		return nil
	}
	out := new(AWSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	in.Filter.DeepCopyInto(&out.Filter)
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CustomFields != nil {
		in, out := &in.CustomFields, &out.CustomFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchOptions) DeepCopyInto(out *ElasticsearchOptions) {
	*out = *in
	in.HostOptions.DeepCopyInto(&out.HostOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchOptions.
func (in *ElasticsearchOptions) DeepCopy() *ElasticsearchOptions {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSOptions) DeepCopyInto(out *GCSOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSOptions.
func (in *GCSOptions) DeepCopy() *GCSOptions {
	if in == nil {
		return nil
	}
	out := new(GCSOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostOptions) DeepCopyInto(out *HostOptions) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostOptions.
func (in *HostOptions) DeepCopy() *HostOptions {
	if in == nil {
		return nil
	}
	out := new(HostOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraOptions) DeepCopyInto(out *JiraOptions) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraOptions.
func (in *JiraOptions) DeepCopy() *JiraOptions {
	if in == nil {
		return nil
	}
	out := new(JiraOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeepaliveConfig) DeepCopyInto(out *KeepaliveConfig) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeepaliveConfig.
func (in *KeepaliveConfig) DeepCopy() *KeepaliveConfig {
	if in == nil {
		return nil
	}
	out := new(KeepaliveConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KinesisOptions) DeepCopyInto(out *KinesisOptions) {
	*out = *in
	out.AWSConfig = in.AWSConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KinesisOptions.
func (in *KinesisOptions) DeepCopy() *KinesisOptions {
	if in == nil {
		return nil
	}
	out := new(KinesisOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiOptions) DeepCopyInto(out *LokiOptions) {
	*out = *in
	in.HostOptions.DeepCopyInto(&out.HostOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiOptions.
func (in *LokiOptions) DeepCopy() *LokiOptions {
	if in == nil {
		return nil
	}
	out := new(LokiOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Options) DeepCopyInto(out *S3Options) {
	*out = *in
	out.AWSConfig = in.AWSConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Options.
func (in *S3Options) DeepCopy() *S3Options {
	if in == nil {
		return nil
	}
	out := new(S3Options)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityHubOptions) DeepCopyInto(out *SecurityHubOptions) {
	*out = *in
	out.AWSConfig = in.AWSConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityHubOptions.
func (in *SecurityHubOptions) DeepCopy() *SecurityHubOptions {
	if in == nil {
		return nil
	}
	out := new(SecurityHubOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackOptions) DeepCopyInto(out *SlackOptions) {
	*out = *in
	in.WebhookOptions.DeepCopyInto(&out.WebhookOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackOptions.
func (in *SlackOptions) DeepCopy() *SlackOptions {
	if in == nil {
		return nil
	}
	out := new(SlackOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkOptions) DeepCopyInto(out *SplunkOptions) {
	*out = *in
	in.HostOptions.DeepCopyInto(&out.HostOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkOptions.
func (in *SplunkOptions) DeepCopy() *SplunkOptions {
	if in == nil {
		return nil
	}
	out := new(SplunkOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetConfig) DeepCopyInto(out *TargetConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetConfig.
func (in *TargetConfig) DeepCopy() *TargetConfig {
	if in == nil {
		return nil
	}
	out := new(TargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TargetConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetConfigList) DeepCopyInto(out *TargetConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TargetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetConfigList.
func (in *TargetConfigList) DeepCopy() *TargetConfigList {
	if in == nil {
		return nil
	}
	out := new(TargetConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TargetConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetConfigSpec) DeepCopyInto(out *TargetConfigSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Options)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Telegram != nil {
		in, out := &in.Telegram, &out.Telegram
		*out = new(TelegramOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.ElasticSearch != nil {
		in, out := &in.ElasticSearch, &out.ElasticSearch
		*out = new(ElasticsearchOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(GCSOptions)
		**out = **in
	}
	if in.Loki != nil {
		in, out := &in.Loki, &out.Loki
		*out = new(LokiOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityHub != nil {
		in, out := &in.SecurityHub, &out.SecurityHub
		*out = new(SecurityHubOptions)
		**out = **in
	}
	if in.Kinesis != nil {
		in, out := &in.Kinesis, &out.Kinesis
		*out = new(KinesisOptions)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = new(WebhookOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Jira != nil {
		in, out := &in.Jira, &out.Jira
		*out = new(JiraOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.AlertManager != nil {
		in, out := &in.AlertManager, &out.AlertManager
		*out = new(HostOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Splunk != nil {
		in, out := &in.Splunk, &out.Splunk
		*out = new(SplunkOptions)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetConfigSpec.
func (in *TargetConfigSpec) DeepCopy() *TargetConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TargetConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetConfigStatus) DeepCopyInto(out *TargetConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetConfigStatus.
func (in *TargetConfigStatus) DeepCopy() *TargetConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TargetConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelegramOptions) DeepCopyInto(out *TelegramOptions) {
	*out = *in
	in.WebhookOptions.DeepCopyInto(&out.WebhookOptions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelegramOptions.
func (in *TelegramOptions) DeepCopy() *TelegramOptions {
	if in == nil {
		return nil
	}
	out := new(TelegramOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookOptions) DeepCopyInto(out *WebhookOptions) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Keepalive != nil {
		in, out := &in.Keepalive, &out.Keepalive
		*out = new(KeepaliveConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookOptions.
func (in *WebhookOptions) DeepCopy() *WebhookOptions {
	if in == nil {
		return nil
	}
	out := new(WebhookOptions)
	in.DeepCopyInto(out)
	return out
}
