{{- if and .Values.serviceAccount.create .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kyvernoplugin.fullname" . }}-secret-reader
  namespace: {{ include "kyvernoplugin.namespace" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kyvernoplugin.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ include "kyvernoplugin.fullname" . }}-secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: "ServiceAccount"
  name: {{ include "kyvernoplugin.serviceAccountName" . }}
  namespace: {{ include "kyvernoplugin.namespace" . }}
{{- end -}}
