{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ui.fullname" . }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "ui.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "policyreporter.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8080
  {{- if or .Values.plugins.kyverno .Values.global.plugins.kyverno }}
  - to:
    - podSelector:
        matchLabels:
          {{- include "kyvernoplugin.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8080
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
