{{- if (gt (int .Values.replicaCount) 1) }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
{{- include "policyreporter.podDisruptionBudget" . | indent 2 }}
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
{{- end }}