{{- if and .Values.serviceAccount.create .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
  name: {{ include "ui.fullname" . }}-secret-reader
  namespace: {{ include "ui.namespace" . }}
rules:
- apiGroups: ['']
  resources:
  - secrets
  verbs:
  - get
{{- end -}}