{{- if .Values.ui.enabled -}}
{{- if .Values.ui.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels: {{- include "ui.labels" . | nindent 4 }}
  name: {{ include "ui.fullname" . }}
  namespace: {{ include "policyreporter.namespace" . }}
spec:
  podSelector:
    matchLabels: {{- include "ui.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- with .Values.ui.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.ui.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}