/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	targetconfigv1alpha1 "github.com/kyverno/policy-reporter/pkg/crd/api/targetconfig/v1alpha1"
	scheme "github.com/kyverno/policy-reporter/pkg/crd/client/clientset/versioned/scheme"
)

// TargetConfigsGetter has a method to return a TargetConfigInterface.
// A group's client should implement this interface.
type TargetConfigsGetter interface {
	TargetConfigs(namespace string) TargetConfigInterface
}

// TargetConfigInterface has methods to work with TargetConfig resources.
type TargetConfigInterface interface {
	Create(ctx context.Context, targetConfig *targetconfigv1alpha1.TargetConfig, opts v1.CreateOptions) (*targetconfigv1alpha1.TargetConfig, error)
	Update(ctx context.Context, targetConfig *targetconfigv1alpha1.TargetConfig, opts v1.UpdateOptions) (*targetconfigv1alpha1.TargetConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, targetConfig *targetconfigv1alpha1.TargetConfig, opts v1.UpdateOptions) (*targetconfigv1alpha1.TargetConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*targetconfigv1alpha1.TargetConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*targetconfigv1alpha1.TargetConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *targetconfigv1alpha1.TargetConfig, err error)
	TargetConfigExpansion
}

// targetConfigs implements TargetConfigInterface
type targetConfigs struct {
	*gentype.ClientWithList[*targetconfigv1alpha1.TargetConfig, *targetconfigv1alpha1.TargetConfigList]
}

// newTargetConfigs returns a TargetConfigs
func newTargetConfigs(c *PolicyreporterV1alpha1Client, namespace string) *targetConfigs {
	return &targetConfigs{
		gentype.NewClientWithList[*targetconfigv1alpha1.TargetConfig, *targetconfigv1alpha1.TargetConfigList](
			"targetconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *targetconfigv1alpha1.TargetConfig { return &targetconfigv1alpha1.TargetConfig{} },
			func() *targetconfigv1alpha1.TargetConfigList { return &targetconfigv1alpha1.TargetConfigList{} },
		),
	}
}
