/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"

	targetconfigv1alpha1 "github.com/kyverno/policy-reporter/pkg/crd/api/targetconfig/v1alpha1"
)

// EmailReportLister helps list EmailReports.
// All objects returned here must be treated as read-only.
type EmailReportLister interface {
	// List lists all EmailReports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*targetconfigv1alpha1.EmailReport, err error)
	// EmailReports returns an object that can list and get EmailReports.
	EmailReports(namespace string) EmailReportNamespaceLister
	EmailReportListerExpansion
}

// emailReportLister implements the EmailReportLister interface.
type emailReportLister struct {
	listers.ResourceIndexer[*targetconfigv1alpha1.EmailReport]
}

// NewEmailReportLister returns a new EmailReportLister.
func NewEmailReportLister(indexer cache.Indexer) EmailReportLister {
	return &emailReportLister{listers.New[*targetconfigv1alpha1.EmailReport](indexer, targetconfigv1alpha1.Resource("emailreport"))}
}

// EmailReports returns an object that can list and get EmailReports.
func (s *emailReportLister) EmailReports(namespace string) EmailReportNamespaceLister {
	return emailReportNamespaceLister{listers.NewNamespaced[*targetconfigv1alpha1.EmailReport](s.ResourceIndexer, namespace)}
}

// EmailReportNamespaceLister helps list and get EmailReports.
// All objects returned here must be treated as read-only.
type EmailReportNamespaceLister interface {
	// List lists all EmailReports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*targetconfigv1alpha1.EmailReport, err error)
	// Get retrieves the EmailReport from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*targetconfigv1alpha1.EmailReport, error)
	EmailReportNamespaceListerExpansion
}

// emailReportNamespaceLister implements the EmailReportNamespaceLister
// interface.
type emailReportNamespaceLister struct {
	listers.ResourceIndexer[*targetconfigv1alpha1.EmailReport]
}
