name: release-image
on:
  push:
    tags:
      - "v*"

    paths-ignore:
      - README.md
      - charts/**
      - manifest/**

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  goreleaser:
    permissions:
      contents: write
      id-token: write
      packages: write
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
      image: ${{ steps.digest.outputs.image }}
      digest: ${{ steps.digest.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: false

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      
      - name: Fetch all tags
        run: |
          set -e
          git fetch --force --tags

      - name: Login to Github Packages
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #v4.0.0
        id: buildx
        with:
          install: true
          version: latest

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@17ae1740179002c89186b61233e0f892c3118b11 # v0.23.0

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --timeout 90m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KOCACHE: /tmp/ko-cache

      - name: Upload artifacts.json
        uses: svenstaro/upload-release-action@b98a3b12e86552593f3e4e577ca8a62aa2f3f22b # 2.11.4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/artifacts.json
          asset_name: artifacts.json
          tag: ${{ github.ref }}

      - name: Upload metadata.json
        uses: svenstaro/upload-release-action@b98a3b12e86552593f3e4e577ca8a62aa2f3f22b # 2.11.4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/metadata.json
          asset_name: metadata.json
          tag: ${{ github.ref }}

      - name: Upload digest.txt
        uses: svenstaro/upload-release-action@b98a3b12e86552593f3e4e577ca8a62aa2f3f22b # 2.11.4
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/digests.txt
          asset_name: digests.txt
          tag: ${{ github.ref }}

      - name: Generate subject
        id: hash
        env:
          ARTIFACTS: "${{ steps.goreleaser.outputs.artifacts }}"
        run: |
          set -euo pipefail
          checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .path')
          hashes=$(cat $checksum_file | base64 -w0)
          echo "hashes=$hashes" >> $GITHUB_OUTPUT

      - name: Image digest
        id: digest
        env:
          ARTIFACTS: "${{ steps.goreleaser.outputs.artifacts }}"
        run: |
          set -euo pipefail
          digest=$(echo "$ARTIFACTS" | jq -rs '.[] | map(select (.type=="Docker Image"))| first | .extra.Digest')
          image_with_tag=$(echo "$ARTIFACTS" | jq -rs '.[] | map(select (.type=="Docker Image"))| first | .path')
          image=$(echo "${image_with_tag}" | cut -d':' -f1)
          echo "image=$image" >> "$GITHUB_OUTPUT"
          echo "digest=$digest" >> "$GITHUB_OUTPUT"

  provenance:
    needs:
      - goreleaser
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.goreleaser.outputs.hashes }}"
      upload-assets: true

  image-provenance:
    needs:
      - goreleaser
    permissions:
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.goreleaser.outputs.image }}
      digest: ${{ needs.goreleaser.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}